# Generated by Django 5.1.3 on 2024-11-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('dish_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('menu_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('process_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('process_output', models.CharField(max_length=255)),
                ('process_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('food_description', models.TextField()),
                ('food_price', models.FloatField()),
                ('dish_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.dishtype')),
            ],
        ),
        migrations.CreateModel(
            name='DishTypeFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.dishtype')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.allergen')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.fooditem')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MenuFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.fooditem')),
                ('menu_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.menu')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.cuisine')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.menu')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_uploader.restaurant')),
            ],
        ),
    ]
