# Generated by Django 5.1.3 on 2024-11-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='dish_type_id',
        ),
    ]
