# Generated by Django 5.1.3 on 2024-12-02 21:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('dish_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255, unique=True)),
                ('food_description', models.TextField()),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('menu_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('process_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('process_output', models.CharField(max_length=255)),
                ('process_message', models.TextField()),
                ('process_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DishTypeFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dishtype')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.allergen')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fooditem')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MenuFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fooditem')),
                ('menu_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.menu')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cuisine')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.menu')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant')),
            ],
            options={
                'unique_together': {('restaurant_id', 'menu_version_id')},
            },
        ),
    ]
